name: Python NLP

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build_windows:
    runs-on: ubuntu-latest
    steps:
      - name: Print Tag
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "Tag: ${{ github.ref_name }}"
          else
            echo "Branch: ${{ github.ref_name }}"
          fi
