name: Python NLP

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build_windows:
    runs-on: ubuntu-latest
    steps:
      - name: Print Tag
        run: echo ${{github.ref_name}}
