name: Python NLP

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build_windows:
    runs-on: ubuntu-latest
    steps:
      - name: Print Tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "Tag: ${GITHUB_REF#refs/tags/}"
          else
            echo "Branch: ${GITHUB_REF#refs/heads/}"
          fi
